version: '3.7'

services:
  database:
    image: postgres
    container_name: database_school
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=@database_school
      - POSTGRES_DB=school_academy
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: school
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
